spring.application.name=projeto_conta_bancaria

# ===============================
# Configuração do Admin Provisório
# ===============================
sistema.admin.email=admin@senai.com
sistema.admin.senha=admin123


# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/contabancaria?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=senaisp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Configuração JWT (exemplo)
# ===============================
# ${JWT_SECRET}
security.jwt.secret=mysupersecretkeymysupersecretkey123!
security.jwt.expiration=600